# Generated by Django 5.2.3 on 2025-07-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_portfoliotechnology'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='build_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
