# Generated by Django 5.2.4 on 2025-07-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_user_build_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfoliotechnology',
            unique_together={('category', 'name')},
        ),
    ]
