# Generated by Django 5.2.4 on 2025-07-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_alter_portfoliotechnology_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_pref',
            field=models.CharField(default='light', max_length=16),
        ),
    ]
